name: Selenium Framework CI

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      BRANDNESS_USERNAME: ${{ secrets.BRANDNESS_USERNAME }}
      BRANDNESS_PASSWORD: ${{ secrets.BRANDNESS_PASSWORD }}

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Verify Maven
        run: mvn -version

      - name: Build Framework
        run: mvn clean compile